#!/usr/bin/env python3
"""
WAF Detector
--------------
Identifies which Web Application Firewall (if any) sits in front of
a target by:
  1. Checking normal-response headers/cookies for WAF-specific
     fingerprints (e.g. Cloudflare's cf-ray, Sucuri's X-Sucuri-ID).
  2. Sending a deliberately malicious-looking test request (a classic
     SQLi-style payload in a query param) and checking whether the
     WAF blocks it with a recognizable challenge/block page — many
     WAFs only reveal themselves when provoked, not on a clean request.

Knowing the WAF in front of a target tells you what evasion research
to focus on and sets expectations for how aggressive scanning can be
before you get blocked entirely.

Intended for use ONLY against systems you own or are explicitly
authorized to test.

Usage:
    python waf_detector.py --url https://target.com
"""

import argparse
import sys

import requests

# (WAF name, header_name, value_pattern_or_None) — None means "presence of header is enough"
HEADER_SIGNATURES = [
    ("Cloudflare", "cf-ray", None),
    ("Cloudflare", "cf-cache-status", None),
    ("Cloudflare", "Set-Cookie", "__cfduid"),
    ("Cloudflare", "Server", "cloudflare"),
    ("Sucuri", "X-Sucuri-ID", None),
    ("Sucuri", "X-Sucuri-Cache", None),
    ("Akamai", "X-Akamai-Transformed", None),
    ("Akamai", "Server", "AkamaiGHost"),
    ("Imperva/Incapsula", "X-Iinfo", None),
    ("Imperva/Incapsula", "Set-Cookie", "incap_ses"),
    ("Imperva/Incapsula", "Set-Cookie", "visid_incap"),
    ("AWS WAF/CloudFront", "X-Amz-Cf-Id", None),
    ("AWS WAF/CloudFront", "Server", "CloudFront"),
    ("F5 BIG-IP ASM", "Set-Cookie", "TS0"),
    ("F5 BIG-IP ASM", "Set-Cookie", "BIGipServer"),
    ("Barracuda", "Set-Cookie", "barra_counter_session"),
    ("Fortinet FortiWeb", "Set-Cookie", "FORTIWAFSID"),
    ("Citrix NetScaler", "Set-Cookie", "ns_af"),
    ("Citrix NetScaler", "Set-Cookie", "citrix_ns_id"),
    ("Wordfence (WordPress)", "Server", "wordfence"),
]

# Block-page body signatures, seen when a WAF actively rejects a malicious-looking request
BLOCK_PAGE_SIGNATURES = [
    ("Cloudflare", "attention required! | cloudflare"),
    ("Cloudflare", "cloudflare ray id"),
    ("Sucuri", "sucuri website firewall"),
    ("Sucuri", "access denied - sucuri website firewall"),
    ("Akamai", "access denied"),
    ("Imperva/Incapsula", "incapsula incident id"),
    ("AWS WAF", "the request could not be satisfied"),
    ("F5 BIG-IP ASM", "the requested url was rejected"),
    ("Barracuda", "barracuda"),
    ("ModSecurity", "mod_security"),
    ("ModSecurity", "this error was generated by mod_security"),
    ("Generic WAF", "web application firewall"),
]

# A classic, unmistakably malicious-looking payload — designed purely to trigger a WAF's
# signature-based rules, not to actually exploit anything
PROVOCATION_PAYLOAD = "?id=1' OR '1'='1'-- -<script>alert(1)</script>../../../etc/passwd"


def check_header_signatures(headers):
    hits = []
    for waf_name, header_name, pattern in HEADER_SIGNATURES:
        value = headers.get(header_name)
        if value is None:
            # also check Set-Cookie-style patterns against the raw cookie jar if header itself absent
            continue
        if pattern is None or pattern.lower() in value.lower():
            hits.append((waf_name, f"header '{header_name}'" + (f": {value}" if pattern is None else f" contains '{pattern}'")))
    return hits


def check_cookie_signatures(raw_cookie_headers):
    hits = []
    combined = " ".join(raw_cookie_headers).lower()
    for waf_name, header_name, pattern in HEADER_SIGNATURES:
        if header_name.lower() != "set-cookie" or not pattern:
            continue
        if pattern.lower() in combined:
            hits.append((waf_name, f"cookie contains '{pattern}'"))
    return hits


def check_block_page(body):
    hits = []
    if not body:
        return hits
    lower = body.lower()
    for waf_name, signature in BLOCK_PAGE_SIGNATURES:
        if signature in lower:
            hits.append((waf_name, f"block-page text matched: '{signature}'"))
    return hits


def get_raw_set_cookie(resp):
    try:
        return resp.raw.headers.getlist("Set-Cookie")
    except AttributeError:
        return [resp.headers["Set-Cookie"]] if "Set-Cookie" in resp.headers else []


def main():
    parser = argparse.ArgumentParser(description="Identify the WAF (if any) in front of a target.")
    parser.add_argument("--url", required=True, help="Target URL, e.g. https://target.com")
    parser.add_argument("--timeout", type=float, default=10.0, help="Request timeout in seconds")
    parser.add_argument("--skip-provocation", action="store_true", help="Skip the malicious-payload test (passive header check only)")
    args = parser.parse_args()

    print(f"[*] Target: {args.url}")
    print("-" * 60)

    all_hits = {}

    def record(hits):
        for waf_name, detail in hits:
            all_hits.setdefault(waf_name, []).append(detail)

    try:
        normal_resp = requests.get(args.url, timeout=args.timeout)
    except requests.RequestException as e:
        print(f"[!] Request failed: {e}", file=sys.stderr)
        sys.exit(1)

    print("[*] Checking normal-response headers/cookies...")
    record(check_header_signatures(normal_resp.headers))
    record(check_cookie_signatures(get_raw_set_cookie(normal_resp)))

    if not args.skip_provocation:
        print("[*] Sending a provocation payload to trigger active WAF blocking...")
        provoked_url = args.url.rstrip("/") + "/" + PROVOCATION_PAYLOAD
        try:
            provoked_resp = requests.get(provoked_url, timeout=args.timeout)
            record(check_header_signatures(provoked_resp.headers))
            record(check_cookie_signatures(get_raw_set_cookie(provoked_resp)))
            record(check_block_page(provoked_resp.text))

            if provoked_resp.status_code in (403, 406, 419, 429, 503) and provoked_resp.status_code != normal_resp.status_code:
                print(f"    [*] Provocation triggered a status change: {normal_resp.status_code} -> {provoked_resp.status_code}")
                if not all_hits:
                    print("    [*] Status change without a specific signature match — a WAF/filter")
                    print("        is likely present but not one in this tool's signature list.")
        except requests.RequestException as e:
            print(f"    [!] Provocation request failed: {e}")

    print("-" * 60)
    if all_hits:
        print("[!] WAF DETECTED:")
        for waf_name, details in all_hits.items():
            print(f"    {waf_name}")
            for d in details[:3]:
                print(f"        - {d}")
    else:
        print("[*] No known WAF signature matched. This does not guarantee no WAF is present —")
        print("    some WAFs are configured to be silent/transparent, or use custom, unlisted")
        print("    signatures. Try --skip-provocation removed (default) or test with a more")
        print("    aggressive payload set if you suspect a WAF is still filtering silently.")


if __name__ == "__main__":
    main()
